### ISSUE TITLE
Tasks for mTurk Experiment Launch

### ISSUE THREAD

**Issue by manaswisaha** [manaswis/cmsc634_sidewalk-mTurk#7]
Tasks related to the system
- [x] Add database tables to track turkers, conditions, routes, sessions, hits @manaswis
- [x] Generate routes of certain distance and from certain selected neighborhoods @maddalihanumateja 
- [x] Modify mission code to load these routes - make appropriate code changes @manaswis
- [x] Remove jump mechanism from the UI (since routes are fixed and verified) @manaswis 
- [x] Verify routes by the researchers to make sure they are ALL walkable (everyone)
- [x] Add new onboarding code and test it @EdigaHe 
- [x] Empty database tables for the main mturk experiments @manaswis

Tasks related to other mTurk related things
- [x] Create batches/groups of HITs @misaugstad or @maddalihanumateja 
- [x] Look into what additional cost mTurk puts for requesters and how does that affect our costing scheme @misaugstad 
- [x] Script to automatically download results from mTurk @misaugstad

**Comment by misaugstad** [comment]
Re: "Look into what additional cost mTurk puts for requesters and how does that affect our costing scheme"

According to [the mturk pricing guide](https://requester.mturk.com/pricing), they charge us a 20% on what we pay the turkers. If we had 10 or more assignments per hit, it would be 40%, but we only have 5 assignments per HIT, so we are charged 20%!

We will also be charged an additional 5% fee if we want to restrict to users who have the "masters qualification", which is just a qualification that Amazon has that says that they typically perform well (may give us higher quality data).

We are planning on paying $0.85 per assignment. So with the masters qualification it would cost us 0.85\*1.25 = $1.06 per assignment. Without the masters qualification, it would cost us 0.85\*1.2 = $1.02 per assignment.

Side note! When performing the experiment for the final study (for CHI, not class), maybe we should calculate how much to charge from how long it takes turkers to audit during this pilot instead of from volunteer data (will likely be cheaper for us).

**Comment by misaugstad** [comment]
Just to make sure we are all on the same page as far as mturk terms go...
HIT: a route that we "assign" to 5 unique turkers, we will have 30 HITs
assignment: there will be 5 assignments per HIT, meaning that we will end up with 150 assignments (30x50)
See [this page](http://docs.aws.amazon.com/AWSMechTurk/latest/RequesterUI/mechanical-turk-concepts.html) for relevant info.

**Comment by misaugstad** [comment]
[It turns out](http://stackoverflow.com/questions/26810757/way-to-create-a-batch-in-mechanical-turk) that you can't create batches of HITs from the API. I am assuming because batches are just provided as a convenience for people who use the UI instead of the API, because entering each HIT by hand would be terrible. So we should just create our HITs one at a time through the API.

**Comment by misaugstad** [comment]
Does that mean to create multiple HITs, all we need to do is loop over the creat_hit() call in test_hit_creation.py? As far as I can tell, that is all we need to do, since things like assignment ID, hit ID, etc, are appended to the external URL so it seems like we don't need to change anything when creating a bunch of HITs that look the same. The only thing I could think of is if we should add a "unique request token" to each HIT we submit, which is a parameter to create_hit() (see [documentation](http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_CreateHITOperation.html)). But someone who knows more about how HITs are submitted should weigh in.

**Comment by maddalihanumateja** [comment]
Mikey we need to create as many HIT as the number of times we want a single user to work on them.
Each HIT has a maximum number of assignments which denotes the number of unique workers that we can have working on that HIT.

So if we have 30 routes and we want atleast 5 people working on each then we can associate each HIT with a route (giving us 30 HITs) and give it a max_assignments = 5

**Comment by misaugstad** [comment]
Nice job all!
